baseURL = "http://austinpoetlaureate.com/"
title = "Austin Poet Laureate"
paginate = 0
theme = "PaperMod"

enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

[minify]
disableXML = true
minifyOutput = true

[params]
title = "Austin Poet Laureate"
description = "Application by Bijan Rahnamai"
defaultTheme = "light"
disableThemeToggle = true
defaultContentLanguage = "en"
ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true

[params.profileMode]
enabled = true
title = "Austin Poet Laureate"
subtitle = "Application by Bijan Rahnamai"
imageUrl = "/images/artist-bijan.jpg"
imageTitle = "Bijan Poet Laureate"

[[params.profileMode.buttons]]
name = "Poems"
url = "poems"

[[params.profileMode.buttons]]
name = "Bio"
url = "bio"

[[params.profileMode.buttons]]
name = "Resume"
url = "resume"

[[params.profileMode.buttons]]
name = "Vision"
url = "vision"

[[menu.main]]
identifier = "poems"
name = "Poems"
url = "/poems/"
weight = 1

[[menu.main]]
identifier = "bio"
name = "Bio"
url = "/bio/"
weight = 2

[[menu.main]]
identifier = "resume"
name = "Resume"
url = "/resume/"
weight = 3

[[menu.main]]
identifier = "vision"
name = "Vision"
url = "/vision/"
weight = 4

[[params.socialIcons]]
name = "linkedin"
url = "https://www.linkedin.com/in/bijan-rahnamai/"

[[params.socialIcons]]
name = "instagram"
url = "https://www.instagram.com/bijanthelovepoet/"